# Generated by Django 3.0.6 on 2020-05-31 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 31, 7, 0, 41, 681210, tzinfo=utc)),
        ),
    ]
