# Generated by Django 3.0.6 on 2020-05-31 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200531_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 31, 7, 30, 56, 362509, tzinfo=utc)),
        ),
    ]
