# Generated by Django 3.0.6 on 2020-05-31 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200531_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creationDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 31, 7, 31, 7, 207774, tzinfo=utc)),
        ),
    ]
