# Generated by Django 3.0.6 on 2020-05-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200531_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='creationDate',
            new_name='creation_date',
        ),
    ]
