# Generated by Django 3.0.6 on 2020-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200531_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='creation_date',
        ),
    ]
