# Generated by Django 3.0.6 on 2020-05-31 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.date(2020, 5, 31)),
        ),
    ]
