# Generated by Django 3.0.6 on 2020-06-01 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200531_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 6, 17, 27, 389581, tzinfo=utc)),
        ),
    ]
