# Generated by Django 3.0.6 on 2020-06-19 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200602_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateField(default=datetime.date(2020, 6, 19)),
        ),
    ]
