# Generated by Django 2.2.13 on 2020-07-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blog_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='points',
        ),
        migrations.AddField(
            model_name='blog',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
