# Generated by Django 3.1 on 2020-09-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200806_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
    ]
